spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: <<url>>
    username: <<username>>
    password: <<>>
  jpa:
    open-in-view: true
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
server:
  port: <<port>>

localStorage:
  documentService:
    filePathName: <<localStorageDocumentService.filePathName>>